### ISSUE TITLE
Randomness generation for separate measurements seems to be heavily correlated

### ISSUE THREAD

**Issue by pizzasok** [msr-quarc/Liquid#10]
Hi,

I just started experimenting with the simulator and subsequent measurements turned out be heavily correlated. I just initialised a qubit in some state and measured it, and repeated the same process many times. The result was very very strange. It may be the case that randomness generation is just not refreshed frequently enough so that it somehow use the same values for quickly repeated measurements. 

Here is my code:

    #if INTERACTIVE
    #r @".\Liquid1.dll"
    #else 
    namespace Microsoft.Research.Liquid // Tell the compiler our namespace
    #endif

    open Microsoft.Research.Liquid // Get necessary Liquid libraries 
    open Util // General utilities 
    open Operations // Basic gates and operations

    module Script =                     // The script module allows for incremental loading

        let rec measIter (qubit:Qubit) (times:int) =
            let q = Ket(1).Qubits.[0]
            q.StateSet qubit.State
            M[q]
            if q.Bit.v = 0 then
                times
            else
                measIter qubit (times+1)

        [<LQD>] 
        let TestRandom() =
            show "Iterating a measurement on qubit copies:"
            let qubit = Ket(1).Qubits.[0]
            qubit.StateSet(sqrt(0.8),0.0,sqrt(0.2),0.0)
            let p = qubit.Prob1
            for i in [1..10] do
                let rep = measIter qubit 0
                show "First measured |0> after %i repetitions, its probability is %e." rep ((1.0-p)*p**(float rep))

And the result of running it was:

    C:\Liquid\bin>Liquid.exe /s TestRandom.fsx TestRandom()
    0:0000.0/
    0:0000.0/===========================================================================================
    0:0000.0/=    The Language-Integrated Quantum Operations (LIQUi|>) Simulator                       =
    0:0000.0/=        Copyright (c) 2015, Microsoft Corporation                                        =
    0:0000.0/=        If you use LIQUi|> in your research, please follow the guidelines at             =
    0:0000.0/=        https://github.com/msr-quarc/Liquid for citing LIQUi|> in your publications.     =
    0:0000.0/===========================================================================================
    0:0000.0/
    0:0000.0/
    0:0000.0/===========================================================================================
    0:0000.0/=    This is an unregistered copy of LIQUi|>.                                             =
    0:0000.0/=    Please follow the instructions at http://github.com/msr-quarc/Liquid to register.    =
    0:0000.0/===========================================================================================
    0:0000.0/
    0:0000.0/=============== Logging to: Liquid.log opened ================
    Microsoft (R) F# Compiler version 14.0.23020.0
    Copyright (c) Microsoft Corporation. All Rights Reserved.
    0:0000.0/Iterating a measurement on qubit copies:
    0:0000.0/First measured |0> after 0 repetitions, its probability is 8.000000e-001.
    0:0000.0/First measured |0> after 0 repetitions, its probability is 8.000000e-001.
    0:0000.0/First measured |0> after 1829 repetitions, its probability is 0.000000e+000.
    0:0000.0/First measured |0> after 0 repetitions, its probability is 8.000000e-001.
    0:0000.0/First measured |0> after 0 repetitions, its probability is 8.000000e-001.
    0:0000.0/First measured |0> after 0 repetitions, its probability is 8.000000e-001.
    0:0000.0/First measured |0> after 0 repetitions, its probability is 8.000000e-001.
    0:0000.0/First measured |0> after 0 repetitions, its probability is 8.000000e-001.
    0:0000.0/First measured |0> after 0 repetitions, its probability is 8.000000e-001.
    0:0000.0/First measured |0> after 0 repetitions, its probability is 8.000000e-001.
    0:0000.0/=============== Logging to: Liquid.log closed ================

On the third line you can see the trace of an event which should not happen in the lifetime of the universe. A measurement event happened 1829 times in a sequence where each individual event had only 10% chance! I get similar results for about each 3rd test runs.

I do not know if it is relevant but I am running Liquid on a 64 bit Windows 7 OS which runs on a VirtualBox instance hosted by a 64 bit ubuntu machine.

Do you have any clue what is happening under the hood?

**Comment by alan-geller** [comment]
@pizzasok: A new pseudorandom number generator is created every time you create a new Ket. The generator is seeded with the current system tick count, which is updated rather infrequently in general, especially on VMs. Thus, the behavior you're seeing is expected.
A better practice is to create one Ket object, and then use the Ket.Reset method when you want to reinitialize. That way you'll use a single random sequence, and should get good statistics.

**Comment by pizzasok** [comment]
Thank you for the reply, I tried not to make new Ket instances and it works indeed. My new code is:

    #if INTERACTIVE
    #r @".\Liquid1.dll"
    #else 
    namespace Microsoft.Research.Liquid // Tell the compiler our namespace
    #endif

    open Microsoft.Research.Liquid // Get necessary Liquid libraries 
    open Util // General utilities 
    open Operations // Basic gates and operations


    module Script =                     // The script module allows for incremental loading

        let rec measIter (ket:Ket) (times:int) =
            let qubitState = ket.Qubits.[0].State
            M[ket.Qubits.[0]]
            let m = ket.Qubits.[0].Bit.v
            //(ket.Reset 1).[0].StateSet qubitState
            ket.Qubits.[0].ReAnimate qubitState
            if m = 0 then
                printf "0 "
                times
            else
                printf "1 "
                measIter ket (times+1)

        [<LQD>] 
        let TestRandom() =
            show "Iterating a measurement on qubit copies:"
            let ket = Ket(1)
            ket.Qubits.[0].StateSet(sqrt(0.8),0.0,sqrt(0.2),0.0)
            for i in [1..1000] do
                let p = ket.Qubits.[0].Prob1
                measIter ket 0 |> ignore
            printfn ""

And the result is:

    C:\Liquid\bin>Liquid.exe /s TestRandom.fsx TestRandom()
    0:0000.0/
    0:0000.0/===========================================================================================
    0:0000.0/=    The Language-Integrated Quantum Operations (LIQUi|>) Simulator                       =
    0:0000.0/=        Copyright (c) 2015, Microsoft Corporation                                        =
    0:0000.0/=        If you use LIQUi|> in your research, please follow the guidelines at             =
    0:0000.0/=        https://github.com/msr-quarc/Liquid for citing LIQUi|> in your publications.     =
    0:0000.0/===========================================================================================
    0:0000.0/
    0:0000.0/
    0:0000.0/===========================================================================================
    0:0000.0/=    This is an unregistered copy of LIQUi|>.                                             =
    0:0000.0/=    Please follow the instructions at http://github.com/msr-quarc/Liquid to register.    =
    0:0000.0/===========================================================================================
    0:0000.0/
    0:0000.0/=============== Logging to: Liquid.log opened ================
    Microsoft (R) F# Compiler version 14.0.23020.0
    Copyright (c) Microsoft Corporation. All Rights Reserved.
    0:0000.0/Iterating a measurement on qubit copies:
    0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0 0 1 1 1 0 0 0 0
    0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0
    0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0
    1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0
    0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1
    1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0
    0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 1
    1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0
    1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0
    0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 1 0 1 1 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0
    0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 0 1 0 1
    1 0 0 1 0 1 1 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0
    0 1 1 0 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 0 0 0 0 0 0
    0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0
    0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0
    0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0
    0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0
    0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0
    0:0000.0/=============== Logging to: Liquid.log closed ================

Looks much more random :-)

Thank you for the support!
