### ISSUE TITLE
Liquid.CSMat from Liquid.CMat

### ISSUE THREAD

**Issue by rumschuettel** [msr-quarc/Liquid#13]
Hi, brief question: does Liquid.CSMat "sparsify" the matrix if given a dense CMat? Or does it keep explicit entries for all the zeroes?

**Comment by dbwz8** [comment]
Yes. It will remove all entries sufficiently close to zero as defined by `Complex.Tol` (complex tolerance, which is settable). The default value is `1.0e-18`.  In addition it will sort the row and column values (which is required for the other sparse routines to work). This also happens after every sparse matrix multiply.
