### ISSUE TITLE
circuit drawing bug

### ISSUE THREAD

**Issue by rumschuettel** [msr-quarc/Liquid#16]
Hi!

There's a bug when using controlled gates, with gates which fit "under" the control lane - see attached picture. I don't think there's any parameter in the Gate constructor which controls this, is there?
https://www.dropbox.com/s/t9y0z67wmakxmcr/liquid-bug1.png?dl=0

Thanks a lot!

**Comment by dbwz8** [comment]
You're correct, there's no concept of layering (_LiquidTikZ.tex_ is pretty simple). OTOH, it's layed out in a straightforward table, so you can go in and hand edit (many of our users do just that). Notice that these wires are drawn with `\qwxB` which is a quantum wire that is "bent". You can edit the amount of bend in the definition of `\qwxB` (and `\cwxB` for classical vertical wires). Putting in a bend is usually enough for you to tell where a wire goes when it goes under another (or when there's lots of vertical wires on top of each other).

**Comment by rumschuettel** [comment]
Thanks a lot, that's very helpful!

2016-03-11 4:10 GMT+00:00 Dave Wecker <notifications@github.com>:
